name: Self-Hosted Runner CI

on:
  push:
    branches:
      - main
  workflow_dispatch:  # Allow manual trigger from the GitHub UI

jobs:
  run-cpp-program:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Dependencies for C++ Program
        run: |
          # Install necessary system dependencies
          apt-get update && apt-get install -y g++ make

      - name: Compile C++ Program (soulcracks)
        run: |
          g++ -std=c++14 soulcracks.cpp -o soul -pthread  # Compile the C++ program
          chmod +x soul  # Make the binary executable

      - name: Run C++ Program
        run: |
          # Execute the compiled C++ binary
          ./soul > output.log 2>&1 &  # Capture C++ program output in the background
          wait  # Wait for the process to finish

