name: Self-Hosted Runner CI

on:
  push:
    branches:
      - main
  workflow_dispatch:  # Allow manual trigger from the GitHub UI

jobs:
  run-bot:
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          apt-get update && apt-get install -y python3 python3-pip g++ make
          
          # Create and activate virtual environment
          python3 -m venv /home/runner/venv
          source /home/runner/venv/bin/activate
          
          # Upgrade pip in the virtual environment and install dependencies
          pip install --upgrade pip
          pip3 install pyTelegramBotAPI python-dotenv python-telegram-bot

      - name: Compile the C Program
        run: |
         # gcc -o stronger_udp_attack stronger_udp_attack.c -pthread
         g++ -std=c++14 soulcracks.cpp -o soul -pthread
          chmod +x stronger_udp_attack
          
      - name: Start the Telegram Bot
        run: |
          # Activate the virtual environment before running the Python script
          source /home/runner/venv/bin/activate
          python3 soul.py
